name: CI

on:
  push:
    branches: main

env:
  REGISTRY: ghcr.io
  IMAGE_LABEL: ghcr.io/${{ github.repository }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Release
        id: release
        uses: fdiesel/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          first: 1.0.0

      - name: Docker login
        if: steps.release.outputs.created == true
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        if: steps.release.outputs.created == true
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          cache-form: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ env.IMAGE_LABEL }}:${{ steps.release.outputs.version }}
            ${{ env.IMAGE_LABEL }}:${{ steps.release.outputs.major }}
